format = '$all'
scan_timeout = 10
add_newline = true

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '
disabled = true

[[battery.display]]
threshold = 20
style = 'bold red'

[character]
format = 'Î» '

[cmd_duration]
min_time = 500
show_milliseconds = true

[directory]
truncation_length = 5
truncation_symbol = 'â€¦/'

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'

[dotnet]
style = 'bold blue'

[hostname]
ssh_only = false
format = '[@$hostname](bold dimmed grey) '

[status]
style = 'bg:blue'
symbol = 'ğŸ’£ '
format = '[\[$symbol$status\]]($style) '
disabled = false

[time]
disabled = true

[username]
style_user = 'blue bold'
style_root = 'white bold'
format = '[$user]($style) '
disabled = false
show_always = true
